#pragma once

namespace Tunkio
{
    DWORD FormatMessageMock(DWORD ,LPCVOID,DWORD,DWORD,LPSTR,DWORD,va_list*);
    HANDLE CreateFileMock(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
    BOOL DeviceIoControlMock(HANDLE, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
    BOOL WriteFileMock(HANDLE, LPCVOID, DWORD, LPDWORD, LPOVERLAPPED);
}