name: Clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install tools
      run: |
        sudo apt --yes install clang cmake ninja-build
        sudo apt --yes install libudev-dev qtbase5-dev
        sudo apt --yes install valgrind

    - name: Build
      run: |
        mkdir out
        cd out
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make

    - name: Run unit tests
      run: |
        cd out/TunkioTests
        valgrind --leak-check=yes ./tunkio-tests
