name: Tunkio Cppcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt --yes install cppcheck

    - name: Static analysis
      run: |
        cppcheck --project=Tunkio.cppcheck
