name: GCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install tools
      run: |
        sudo apt --yes install gcc cmake ninja-build
        sudo apt --yes install libudev-dev qtbase5-dev
        sudo apt --yes install valgrind

    - name: Build
      run: |
        mkdir out
        cd out
        export CC=/usr/bin/gcc
        export CXX=/usr/bin/g++
        cmake ..
        make

    - name: Run unit tests
      run: |
        cd out/TunkioTests
        valgrind --leak-check=yes ./tunkio-tests
