name: GCC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install tools
      run: |
        sudo apt update
        sudo apt --yes install g++-10 cmake ninja-build
        sudo apt --yes install libudev-dev
        sudo apt --yes install valgrind
        # sudo apt --yes install qtbase6-dev not yet available...

    - name: Build
      run: |
        mkdir out
        cd out
        export CC=/usr/bin/gcc-10
        export CXX=/usr/bin/g++-10
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DKUURA_SKIP_GUI_BUILD=True ..
        ninja

    - name: Run unit tests
      run: |
        cd out
        valgrind --leak-check=yes ./kuura-tests
